import {
  User,
  Blocks,
  Command,
  BookOpen,
  Settings,
  Calendar,
  Settings2,
  AudioWaveform,
  GalleryVerticalEnd,
  LayoutList,
  Group,
  Building2,
  LibraryBig,
  Split,
  NotebookText,
  Users,
  Contact,
  CalendarSearch,
  CalendarOff,
  CalendarArrowUp,
  FileSearch,
  SquareUser,
  NotepadText,
  Notebook,
  BookUser,
  SquareChartGantt,
  ChartArea,
  ClipboardPlus,
  ScrollText,
  CalendarDays,
} from "lucide-react"

import { APP_ROUTES } from "@/constants/app-routes"

export const navData = {
  user: {
    name: "Пташник Роман",
    email: "ptashnyk.roman@pharm.zt.ua",
    avatar: "./avatars/shadcn.jpg",
  },
  teams: [
    {
      name: "ЖБФФК",
      logo: GalleryVerticalEnd,
      plan: "ЖОР",
    },
    {
      name: "Acme Corp.",
      logo: AudioWaveform,
      plan: "Startup",
    },
    {
      name: "Evil Corp.",
      logo: Command,
      plan: "Free",
    },
  ],
  navMain: [
    {
      id: "1",
      title: "Структура",
      key: "structure",
      icon: Blocks,
      items: [
        {
          id: "1",
          title: "Групи",
          url: APP_ROUTES.GROUPS,
          icon: LayoutList,
        },
        {
          id: "2",
          title: "Потоки",
          url: APP_ROUTES.STREAMS,
          icon: Group,
        },
        {
          id: "3",
          title: "Аудиторії",
          url: APP_ROUTES.AUDITORIES,
          icon: Building2,
        },
      ],
    },
    {
      id: "2",
      title: "Навантаження",
      key: "load",
      icon: BookOpen,
      items: [
        {
          id: "4",
          title: "Навчальні плани",
          url: APP_ROUTES.PLANS,
          icon: LibraryBig,
        },
        {
          id: "5",
          title: "Розподіл навантаження",
          url: APP_ROUTES.DISTRIBUTION,
          icon: Split,
        },
        {
          id: "6",
          title: "Перегляд навантаження",
          url: APP_ROUTES.VIEW_DISTRIBUTION_LOAD,
          icon: NotebookText,
        },
      ],
    },
    {
      id: "3",
      title: "Облікові записи",
      key: "accounts",
      icon: User,
      items: [
        {
          id: "7",
          title: "Педагогічний склад",
          url: APP_ROUTES.TEACHERS,
          icon: User,
        },
        {
          id: "8",
          title: "Здобувачі освіти",
          url: APP_ROUTES.STUDENTS,
          icon: Contact,
        },
        {
          id: "9",
          title: "Поділ на підгрупи",
          url: APP_ROUTES.STUDENTS_DIVIDE,
          icon: Users,
        },
      ],
    },
    {
      id: "4",
      title: "Розклад",
      key: "timetable",
      icon: Calendar,
      items: [
        {
          id: "10",
          title: "Редактор розкладу",
          url: APP_ROUTES.TIMETABLE,
          icon: CalendarDays,
        },
        {
          id: "11",
          title: "Автоматичне розставлення",
          url: "#",
          icon: CalendarArrowUp,
        },
        {
          id: "12",
          title: "Обмеження розкладу",
          url: "#",
          icon: CalendarOff,
        },
        {
          id: "13",
          title: "Контроль вичитки",
          url: APP_ROUTES.TIMETABLE_CONTROL,
          icon: CalendarSearch,
        },
        {
          id: "14",
          title: "Мій розклад",
          url: APP_ROUTES.MY_TIMETABLE,
          icon: Calendar,
        },
        {
          id: "15",
          title: "Пошук вільної аудиторії",
          url: APP_ROUTES.FIND_FREE_AUDITORY,
          icon: FileSearch,
        },
      ],
    },
    {
      id: "5",
      title: "Загальне",
      key: "general",
      icon: Settings2,
      items: [
        {
          id: "16",
          title: "Мій профіль",
          url: APP_ROUTES.PROFILE,
          icon: SquareUser,
        },
        {
          id: "17",
          title: "Вибіркові дисципліни",
          url: "#",
          icon: SquareUser,
        },
        {
          id: "18",
          title: "Електронний журнал",
          url: APP_ROUTES.GRADE_BOOK,
          icon: BookOpen,
        },
        {
          id: "19",
          title: "Навчально-метдичні комплекси",
          url: APP_ROUTES.INSTRUCTIONAL_MATERIALS,
          icon: LibraryBig,
        },
        {
          id: "20",
          title: "Індивідуальний план роботи викладача",
          url: APP_ROUTES.INDIVIDUAL_TEACHER_WORK,
          icon: Notebook,
        },
        {
          id: "21",
          title: "Види педагогічної діяльності",
          url: APP_ROUTES.TEACHER_ACTIVITIES_TYPES,
          icon: BookUser,
        },
        {
          id: "22",
          title: "Звіт викладача",
          url: APP_ROUTES.TEACHERS_REPORT,
          icon: NotepadText,
        },
        {
          id: "23",
          title: "Моє педагогічне навантаження",
          url: APP_ROUTES.MY_TEACHING_LOAD,
          icon: SquareChartGantt,
        },
      ],
    },
    {
      id: "6",
      title: "Налаштування",
      key: "settings",
      icon: Settings,
      items: [
        {
          id: "24",
          title: "Налаштування",
          url: APP_ROUTES.SETTINGS,
          icon: Settings,
        },
        {
          id: "25",
          title: "Статистика",
          url: "#",
          icon: ChartArea,
        },
        {
          id: "26",
          title: "Звіти",
          url: "#",
          icon: ClipboardPlus,
        },
        {
          id: "27",
          title: "Документація",
          url: "#",
          icon: ScrollText,
        },
      ],
    },
  ],
}
