import {
  User,
  Blocks,
  Command,
  BookOpen,
  Settings,
  Calendar,
  Settings2,
  AudioWaveform,
  GalleryVerticalEnd,
  LayoutList,
  Group,
  Building2,
  LibraryBig,
  Split,
  NotebookText,
  Users,
  Contact,
  CalendarSearch,
  CalendarOff,
  CalendarArrowUp,
  FileSearch,
  SquareUser,
  NotepadText,
  Notebook,
  BookUser,
  SquareChartGantt,
  ChartArea,
  ClipboardPlus,
  ScrollText,
  CalendarDays,
} from "lucide-react"

export const navData = {
  user: {
    name: "Пташник Роман",
    email: "ptashnyk.roman@pharm.zt.ua",
    avatar: "./avatars/shadcn.jpg",
  },
  teams: [
    {
      name: "ЖБФФК",
      logo: GalleryVerticalEnd,
      plan: "ЖОР",
    },
    {
      name: "Acme Corp.",
      logo: AudioWaveform,
      plan: "Startup",
    },
    {
      name: "Evil Corp.",
      logo: Command,
      plan: "Free",
    },
  ],
  navMain: [
    {
      id: "1",
      title: "Структура",
      key: "structure",
      icon: Blocks,
      items: [
        {
          id: "1",
          title: "Групи",
          url: "/groups",
          icon: LayoutList,
        },
        {
          id: "2",
          title: "Потоки",
          url: "/streams",
          icon: Group,
        },
        {
          id: "3",
          title: "Аудиторії",
          url: "/auditories",
          icon: Building2,
        },
      ],
    },
    {
      id: "2",
      title: "Навантаження",
      key: "load",
      icon: BookOpen,
      items: [
        {
          id: "4",
          title: "Навчальні плани",
          url: "/plans",
          icon: LibraryBig,
        },
        {
          id: "5",
          title: "Розподіл навантаження",
          url: "/distribution",
          icon: Split,
        },
        {
          id: "6",
          title: "Перегляд навантаження",
          url: "/view-distribution-load",
          icon: NotebookText,
        },
      ],
    },
    {
      id: "3",
      title: "Облікові записи",
      key: "accounts",
      icon: User,
      items: [
        {
          id: "7",
          title: "Педагогічний склад",
          url: "/teachers",
          icon: User,
        },
        {
          id: "8",
          title: "Здобувачі освіти",
          url: "/students",
          icon: Contact,
        },
        {
          id: "9",
          title: "Поділ на підгрупи",
          url: "/students-divide",
          icon: Users,
        },
      ],
    },
    {
      id: "4",
      title: "Розклад",
      key: "timetable",
      icon: Calendar,
      items: [
        {
          id: "10",
          title: "Редактор розкладу",
          url: "/timetable",
          icon: CalendarDays,
        },
        {
          id: "11",
          title: "Автоматичне розставлення",
          url: "#",
          icon: CalendarArrowUp,
        },
        {
          id: "12",
          title: "Обмеження розкладу",
          url: "#",
          icon: CalendarOff,
        },
        {
          id: "13",
          title: "Контроль вичитки",
          url: "/timetable-control",
          icon: CalendarSearch,
        },
        {
          id: "14",
          title: "Мій розклад",
          url: "/my-timetable",
          icon: Calendar,
        },
        {
          id: "15",
          title: "Пошук вільної аудиторії",
          url: "/find-free-auditory",
          icon: FileSearch,
        },
      ],
    },
    {
      id: "5",
      title: "Загальне",
      key: "general",
      icon: Settings2,
      items: [
        {
          id: "16",
          title: "Мій профіль",
          url: "/profile",
          icon: SquareUser,
        },
        {
          id: "17",
          title: "Вибіркові дисципліни",
          url: "#",
          icon: SquareUser,
        },
        {
          id: "18",
          title: "Електронний журнал",
          url: "/grade-book",
          icon: BookOpen,
        },
        {
          id: "19",
          title: "Навчально-метдичні комплекси",
          url: "/instructional-materials",
          icon: LibraryBig,
        },
        {
          id: "20",
          title: "Індивідуальний план роботи викладача",
          url: "/individual-teacher-work",
          icon: Notebook,
        },
        {
          id: "21",
          title: "Види педагогічної діяльності",
          url: "/teacher-activities-types",
          icon: BookUser,
        },
        {
          id: "22",
          title: "Звіт викладача",
          url: "/teachers-report",
          icon: NotepadText,
        },
        {
          id: "23",
          title: "Моє педагогічне навантаження",
          url: "/my-teaching-load",
          icon: SquareChartGantt,
        },
      ],
    },
    {
      id: "6",
      title: "Налаштування",
      key: "settings",
      icon: Settings,
      items: [
        {
          id: "24",
          title: "Налаштування",
          url: "/settings",
          icon: Settings,
        },
        {
          id: "25",
          title: "Статистика",
          url: "#",
          icon: ChartArea,
        },
        {
          id: "26",
          title: "Звіти",
          url: "#",
          icon: ClipboardPlus,
        },
        {
          id: "27",
          title: "Документація",
          url: "#",
          icon: ScrollText,
        },
      ],
    },
  ],
}
